import {
  FaceSmileIcon,
  ChartBarSquareIcon,
  CursorArrowRaysIcon,
  DevicePhoneMobileIcon,
  AdjustmentsHorizontalIcon,
  SunIcon,
  ChartPieIcon,
} from "@heroicons/react/24/solid";

import benefitOneImg from "../../../public/img/benefit-one.png";
import benefitTwoImg from "../../../public/img/benefit-two.png";

const benefitBypass = {
  title: "AI Bypass - Bypass AI Every Time With 100% Undetectable Content",
  desc: "Generate Human-Like Content. Guaranteed Plagiarism-Free!",
  image: benefitOneImg,
  bullets: [
    {
      title: "Wide Coverage",
      desc: "Covers all popular AI Detectors Like GPTZero, Originality.ai and More.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "High Success Rate",
      desc: "Built-in detection capabilities ensure a 99% success rate.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "Outstanding Features",
      desc: "Plagiarism-free and avoids spam folders.",
      icon: <CursorArrowRaysIcon />,
    },
  ],
};

const benefitDetector = {
  title: "AI Detector - Reliable and Easy to Use",
  desc: "AI Checker for ChatGPT, Claude & More",
  image: benefitTwoImg,
  bullets: [
    {
      title: "Reliable and Easy to Use",
      desc: "90% accuracy rate guaranteed.",
      icon: <DevicePhoneMobileIcon />,
    },
    {
      title: "The Best Way to Detect AI",
      desc: "Covers major large language models like ChatGPT, Claude, Bard/Gemini, and more.",
      icon: <AdjustmentsHorizontalIcon />,
    },
    {
      title: "Designed for Students",
      desc: "Perfect for projects like assignments, research papers, and working drafts.",
      icon: <SunIcon />,
    },
  ],
};

const benefitEssay = {
  title: "AI Essay Writer - Your #1 Paper Writing Assistant ",
  desc: "100% human like , get your A+ essays Faster",
  image: benefitOneImg,
  bullets: [
    {
      title: "AI Writer that Understands",
      desc: "Trained on high-quality essays, our AI understands essay structure and grading criteria.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "Personal Data Safety",
      desc: "Your data is protected and risk-free.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "Multilingual Capabilities",
      desc: "Rephrase text in over 20 languages.",
      icon: <CursorArrowRaysIcon />,
    },
  ],
};

const opsBenefitEssay = {
  title: "AI Essay Writer - Your #1 Paper Writing Assistant ",
  desc: "100% human like , get your A+ essays Faster",
  image: benefitOneImg,
  bullets: [
    {
      title: "Handles a variety of essay formats",
      desc: "From augmentative, descriptive  to narrative essays.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "Deeply understands academic writing conventions",
      desc: "Trained on millions of high-quality essays, ensuring the generation is well-structured and accurate.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "AIWriter.PRO writers for all",
      desc: "support all scientific majors and 200+ languages. ",
      icon: <CursorArrowRaysIcon />,
    },
  ],
};

const opsBenefitDetector = {
  title: "AI Detector - Reliable and Easy to Use",
  desc: "AI Checker for ChatGPT, Claude & More",
  image: benefitTwoImg,
  bullets: [
    {
      title: "Covers all major AI models",
      desc: "Accurately detect text generated by ChatGPT, Claude, Grammarly, Gemini, and other advanced language models.",
      icon: <DevicePhoneMobileIcon />,
    },
    {
      title: "Blazing-fast detection",
      desc: "Scan any document in under a minute with 99% accuracy.",
      icon: <AdjustmentsHorizontalIcon />,
    },
    {
      title: "Multilingual Support",
      desc: "Analyze content in 200+ languages, from academic papers to social media posts.",
      icon: <SunIcon />,
    },
  ],
};

const benefitMindMaker = {
  title: "AI Mind Map Maker",
  desc: "Communicate Ideas Faster and Clearer",
  image: benefitOneImg,
  bullets: [
    {
      title: "Organize Your Thoughts",
      desc: "Create instant, customizable, and shareable visual content in seconds.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "Create from Documented Information",
      desc: "Generate mind maps from PDFs, Word documents, and text.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "I-Driven Expansion for Endless Ideas",
      desc: "Perfect for studying and brainstorming sessions.",
      icon: <CursorArrowRaysIcon />,
    },
  ],
};

const opsBenefitMindMaker = {
  title: "Upercharge Your Brainpower",
  desc: "Why You Need an AI Mind Map Tool",
  image: benefitOneImg,
  bullets: [
    {
      title: "Instant expansion for endless ideas",
      desc: "Mind map tools are extensions of your thought process - and AI makes that process easier by providing endless options to expand. Perfect for brainstorming or quickly studying a new topic.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "Easy start with any number of words",
      desc: "Mind mapping with AI capabilities can start drafting with just one word or specific long instructions, making it suitable for various needs, whether you're starting from scratch or refining an existing idea.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "Quickly processes the thinking task",
      desc: "With us, you can generate and organize ideas in one step, eliminating the need to spend hours structuring information after brainstorming. Everything is ready once the ideas are out.",
      icon: <CursorArrowRaysIcon />,
    }
  ],
};

const opsMindMakerWorks = {
  title: "How It Works",
  desc: "",
  image: benefitOneImg,
  bullets: [
    {
      title: "Describe Your Idea",
      desc: "Simply type a keyword or phrase.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "AI Does the Rest",
      desc: "Watch as your mind map expands with relevant information.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "Refine and Customize",
      desc: "Tweak and tailor your mind map to fit your needs.",
      icon: <CursorArrowRaysIcon />,
    }
  ],
};

const opsMindMakerResults = {
  title: "Tips for Better Results",
  desc: "",
  image: benefitOneImg,
  bullets: [
    {
      title: "Be Specific",
      desc: "The more details you provide, the better the results.",
      icon: <FaceSmileIcon />,
    },
    {
      title: "Experiment and Iterate",
      desc: "Don't be afraid to try different prompts and approaches.",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "Do It Step by Step",
      desc: "break the process into stages and do it at a time.",
      icon: <CursorArrowRaysIcon />,
    }
  ],
};

const opsMindMakerYouCan = {
  title: "By using our AI Mind Map tool, you can: ",
  desc: "",
  image: benefitOneImg,
  bullets: [
    {
      title: "Improve your study habits",
      desc: "",
      icon: <FaceSmileIcon />,
    },
    {
      title: "Boost your creativity",
      desc: "",
      icon: <ChartBarSquareIcon />,
    },
    {
      title: "Enhance your problem-solving skills",
      desc: "",
      icon: <CursorArrowRaysIcon />,
    },
    {
      title: "Enhance your problem-solving skills",
      desc: "",
      icon: <ChartPieIcon />,
    }
  ],
};

const faq = [
  {
    question: "What is AIWriter.PRO?",
    answer: "AIWriter.PRO is an advanced AI writing tool designed to assist students and professionals in crafting high-quality content. It offers a suite of tools, including AI Bypass, AI Detector, AI Essay Writer, and AI Mind Map Maker.",
  },
  {
    question: "How does AIWriter.PRO help students?",
    answer: "AIWriter.PRO empowers students by: *Automating tasks: Streamlining the writing process and saving time.  *Improving quality: Generating well-structured and coherent content. *Ensuring originality: Providing plagiarism-free and AI-undetectable text. *Enhancing creativity: Facilitating brainstorming and idea generation.",
  },
  {
    question: "What is AI Bypass? ",
    answer: "AI Bypass is a tool that rephrases text to evade AI detection. It helps you create or rewrite human-quality content that is indistinguishable from human-written text.",
  },
  {
    question: "How does AI Bypass work? ",
    answer: "AI Bypass utilizes advanced algorithms to rewrite text while preserving its original meaning and style. It can bypass AI detection tools like GPTZero and Originality.ai.",
  },
  {
    question: "What is AI Detector? ",
    answer: "AI Detector is a tool that can accurately identify AI-generated text. It helps you verify the authenticity of content and avoid plagiarism.",
  },
  {
    question: "How accurate is AI Detector? ",
    answer: "AI Detector boasts a high accuracy rate, capable of detecting AI-generated text from various sources, including ChatGPT, Claude, and Bard/Gemini.",
  },
  {
    question: "Can AI Essay Writer write complete essays? ",
    answer: "While AI Essay Writer can assist in generating ideas, outlines, and paragraphs, it is not designed to write entire essays autonomously. It's best used as a tool to enhance your writing process.",
  },
  {
    question: "Is AI Essay Writer safe to use? ",
    answer: "Yes, AI Essay Writer prioritizes data privacy and security. Your personal information is protected, and your content remains confidential.",
  },
  {
    question: "How can AI Mind Map Maker help me? ",
    answer: "AI Mind Map Maker allows you to visualize and organize your thoughts effectively. It can generate mind maps from text, PDFs, and Word documents, helping you brainstorm and plan your work.",
  },
  {
    question: "Can I customize mind maps created with AI Mind Map Maker?",
    answer: "Yes, AI Mind Map Maker offers customization options to tailor your mind maps to your specific needs. You can adjust colors, fonts, and layouts to create visually appealing and informative diagrams.",
  },
  {
    question: "Is AIWriter.PRO free to use?",
    answer: "  - AIWriter.PRO offers a free plan with basic features. For advanced features and unlimited usage, consider upgrading to a premium plan.",
  },
  {
    question: "What languages does AIWriter.PRO support?",
    answer: "  - AIWriter.PRO supports multiple languages, allowing you to generate content in various languages.",
  },
  {
    question: "Can I use AIWriter.PRO for academic writing?",
    answer: "  - While AIWriter.PRO can be a helpful tool for academic writing, it's important to use it responsibly. Always cite your sources and avoid plagiarism.",
  },
  {
    question: "How can I get help with AIWriter.PRO?",
    answer: "  - AIWriter.PRO offers comprehensive customer support through email and a knowledge base.",
  },
];

const essayFaq = [
  {
    question: "What is an AI Essay Writer?",
    answer: "An AI Essay Writer is an advanced artificial intelligence tool designed to assist users in crafting high-quality essays. It leverages advanced language models to generate well-structured, informative, and engaging content.",
  },
  {
    question: "How does the AI Essay Writer work? ",
    answer: "To use the AI Essay Writer, simply input your desired topic, essay type, and any specific requirements. The AI will then process the information and generate a comprehensive essay draft. You can further refine and customize the output to meet your exact needs.",
  },
  {
    question: "Is the AI Essay Writer reliable? ",
    answer: "Yes, the AI Essay Writer is highly reliable. It is trained on a massive dataset of academic texts, ensuring accurate and relevant content.",
  },
  {
    question: "Can the AI Essay Writer help with different essay types?",
    answer: "Absolutely! The AI Essay Writer can assist with a wide range of essay types, including argumentative, descriptive, narrative, and more.",
  },
  {
    question: "Can the AI Essay Writer generate content in multiple languages?",
    answer: "Yes, the AI Essay Writer supports over 200 languages, allowing users to create content in their preferred language.",
  },
  {
    question: "Can I customize the generated content? ",
    answer: "Yes, you can easily customize the generated content to fit your specific needs. You can modify the tone, style, and length of the essay, as well as add or remove specific points.",
  },
  {
    question: "Is it ethical to use an AI Essay Writer",
    answer: "Using an AI Essay Writer as a tool to assist in the writing process is ethical. However, it's important to use it responsibly and to cite any sources used. Always ensure that the generated content is your own work and avoid plagiarism.",
  },
  {
    question: "Can I submit AI-generated content to academic institutions?",
    answer: "While AI-generated content can be a valuable tool for drafting, it's crucial to exercise caution when submitting it to academic institutions. Always ensure that the central idea and arguments are your own original work. Additionally, use our AI detectors to check the originality of the text before submission.",
  }
];

const detectorFaq = [
  {
    question: "What is an AI Detector?",
    answer: "An AI detector is a tool designed to identify text generated by artificial intelligence models, such as ChatGPT, Claude, Grammarly, Gemini, and more. It analyzes text and determines the likelihood that it was written by a human or an AI.",
  },
  {
    question: "How does the AI Detector work?",
    answer: "The AI detector uses advanced machine learning algorithms to analyze various linguistic patterns, stylistic choices, and other factors. By comparing the input text to a large dataset of human-written and AI-generated text, it can accurately determine the origin of the content.",
  },
  {
    question: "Why is an AI Detector important? ",
    answer: "- Academic Integrity: To identify AI-generated academic papers or essays.- Content Authenticity: To verify the authenticity of news articles, blog posts, or social media content.- Copyright Protection: To protect original content from AI-generated plagiarism.",
  },
  {
    question: " Can an AI Detector accurately identify all AI-generated text?",
    answer: "While AI detectors are highly accurate, they are not infallible. As AI models continue to evolve, it becomes increasingly difficult to distinguish between human-generated and AI-generated text. However, advanced AI detectors can achieve high accuracy rates, especially when trained on a diverse dataset.",
  },
  {
    question: "Can I use an AI Detector to improve my own writing?",
    answer: "While AI detectors are primarily designed to identify AI-generated text, they can also be used as a tool to improve your own writing. You can also go to explore our other writing tools",
  }
];

const mindMakerFaq = [
  {
    question: "What is an AI Mind Map Tool? ",
    answer: "An AI Mind Map Tool is a digital tool that helps you visually organize your thoughts and ideas. It uses artificial intelligence to generate and expand upon your initial ideas, making it easier to brainstorm, plan, and study.",
  },
  {
    question: "How does it work? ",
    answer: "Simply input a keyword or phrase, and the AI will generate a mind map with related concepts and ideas. You can then customize and expand upon this initial map to suit your specific needs.",
  },
  {
    question: "Can I use it for studying?",
    answer: "Absolutely! Our AI Mind Map Tool is perfect for studying. You can use it to break down complex topics into smaller, more manageable chunks, visualize information, and create effective study guides.",
  },
  {
    question: "How can it help me with my assignments?",
    answer: "Our tool can help you brainstorm ideas, organize your thoughts, and create visually appealing presentations. It can also help you with research by suggesting relevant keywords and sources.",
  },
  {
    question: "Can I use it for project planning?",
    answer: "Yes, our tool is great for project planning. You can use it to break down large projects into smaller tasks, identify dependencies, and track progress.",
  },
  {
    question: "How can it help me with brainstorming?",
    answer: "Our AI can help you generate new ideas, explore different perspectives, and identify potential solutions.",
  },
  {
    question: "Is it easy to use? ",
    answer: "Yes, our tool is designed to be user-friendly. You don't need any technical expertise to use it.",
  },
  {
    question: "Is my data safe?",
    answer: "- We take data privacy seriously. Your data is securely stored and protected.If you have any other questions, please feel free to contact our support team.",
  }
];


export {
  benefitBypass, benefitDetector, benefitEssay, benefitMindMaker, opsBenefitEssay,
  faq, essayFaq, opsBenefitDetector, detectorFaq, opsBenefitMindMaker, 
  opsMindMakerWorks, opsMindMakerResults, opsMindMakerYouCan, mindMakerFaq
};
