import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChildrenType } from "@/@core/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const direction = 'ltr'
//   return (
//     <html id='__next' dir={direction}>
//       <body className="className='flex is-full min-bs-full flex-auto flex-col'">
//         {children}
//       </body>
//     </html>
//   );
// }
const RootLayout = ({ children }: ChildrenType) => {
  // Vars
  const direction = 'ltr'

  return (
    <html id='__next' dir={direction}>
      <body className='flex is-full min-bs-full flex-auto flex-col'>{children}</body>
    </html>
  )
}

export default RootLayout
